version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g @nestjs/cli
  build:
    commands:
      - npm run deploy

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./

cache:
  paths:
    - node_modules/**/*
