version: '3'
services:
  backend:
    image: 2donny/4oclock-backend
    container_name: app_backend
    mem_limit: 128m

  nginx:
    restart: always
    image: 2donny/4oclock-nginx
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - backend
