version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./4oclock-server
    ports:
      - 3080:3080

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./4oclock-nginx
    ports:
      - "80:80"
