branch-defaults:
  master:
    environment: 4oclockfinal-env-1
environment-defaults:
  4oclockfinal-env-1:
    branch: null
    repository: null
global:
  application_name: 4oclock-final
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
