branch-defaults:
  master:
    environment: 4oclockfinal-env-1
    group_suffix: null
environment-defaults:
  4oclockfinal-env-1:
    branch: master
    repository: 4oclock-final-dev
global:
  application_name: 4oclock-final
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: 4oclockfinal-env-1
  sc: git
  workspace_type: Application
