export const GET_PLACES_BY_LOCATION_CACHE_KEY =
  'GET_PLACES_BY_LOCATION_CACHE_KEY';
export const GET_PLACE_BY_ID_CACHE_KEY = 'GET_PLACE_BY_ID_CACHE_KEY';

export type CUSTOM_CACHE_KEYS =
  | typeof GET_PLACES_BY_LOCATION_CACHE_KEY
  | typeof GET_PLACE_BY_ID_CACHE_KEY;
